#!/usr/bin/env python3
"""Run a bounded number of automatic JIT envelope iterations.

Each round is generated by ``prepare_iterative_envelope_workflow.py`` and
executed by the existing resumable workflow engine.  A failed stage or failed
acceptance gate aborts immediately.  This loop never changes a training recipe,
threshold contract, perturbation panel, or repair strategy in response to an
outcome.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys


PYTHON = "/home/qy/mujoco_playground/.venv/bin/python"


def read(path: Path):
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"JSON object required: {path}")
    return value


def run(command, *, cwd: Path, env: dict[str, str]) -> None:
    result = subprocess.run(command, cwd=cwd, env=env, check=False)
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--selected-policy", type=Path, required=True)
    parser.add_argument("--source-tube", type=Path, required=True)
    parser.add_argument("--max-rounds", type=int, default=1)
    parser.add_argument("--tag-prefix", default="auto")
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    args = parser.parse_args()
    if not 1 <= int(args.max_rounds) <= 10:
        raise ValueError("max-rounds must lie in [1, 10]; unbounded automatic looping is forbidden")

    repo = args.repo_root.resolve()
    env = os.environ.copy()
    env["PYTHONPATH"] = str(repo / "JIT/src")
    env.setdefault("XLA_PYTHON_CLIENT_PREALLOCATE", "false")
    selected_path = args.selected_policy
    tube_path = args.source_tube
    history = []

    for round_index in range(1, int(args.max_rounds) + 1):
        selected = read(selected_path)
        k = int(selected["iteration"])
        if selected.get("status") != "selected" or selected.get("policy_name") != f"pi_{k}":
            raise ValueError("loop source policy is not a selected pi_k artifact")
        next_k = k + 1
        tag = f"{args.tag_prefix}_r{round_index}_k{k}"
        config = Path(f"JIT/configs/auto_envelope_pi{k}_to_pi{next_k}_{tag}.json")
        prepared = config.with_suffix(config.suffix + ".prepared.json")

        if not prepared.is_file():
            run(
                [
                    PYTHON,
                    "JIT/cli/prepare_iterative_envelope_workflow.py",
                    "--selected-policy",
                    str(selected_path),
                    "--source-tube",
                    str(tube_path),
                    "--tag",
                    tag,
                    "--config-out",
                    str(config),
                    "--repo-root",
                    str(repo),
                ],
                cwd=repo,
                env=env,
            )
        prep = read(prepared)
        if int(prep["source_iteration"]) != k or int(prep["candidate_iteration"]) != next_k:
            raise ValueError("prepared workflow iteration drift")

        print(
            f"\n===== AUTO ENVELOPE ROUND {round_index}: pi_{k} -> pi_{next_k} =====",
            flush=True,
        )
        run(
            [PYTHON, "JIT/cli/run_iteration_workflow.py", "--config", str(config), "--execute"],
            cwd=repo,
            env=env,
        )
        next_selected = Path(str(prep["candidate_selected_policy"]))
        next_tube = Path(str(prep["target_tube"]))
        if not next_selected.is_file() or not (next_tube / "manifest.json").is_file():
            raise ValueError("completed round did not produce selected next policy and Tube")
        selected_next_payload = read(next_selected)
        if selected_next_payload.get("formal_acceptance_claim") is not True:
            raise ValueError("automatic loop cannot advance without a formal acceptance PASS")
        history.append(
            {
                "round": round_index,
                "source_iteration": k,
                "candidate_iteration": next_k,
                "workflow_config": str(config),
                "selected_policy": str(next_selected),
                "tube": str(next_tube),
            }
        )
        selected_path = next_selected
        tube_path = next_tube

    report = {
        "schema": "jit_iterative_envelope_loop_report_v1",
        "status": "completed",
        "requested_rounds": int(args.max_rounds),
        "completed_rounds": len(history),
        "history": history,
        "final_selected_policy": str(selected_path),
        "final_source_tube": str(tube_path),
        "automatic_repair_on_failure": False,
        "unbounded_loop": False,
        "test_data_used": False,
    }
    out = Path(f"JIT/runs/iteration_auto/loop_{args.tag_prefix}_summary.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, sort_keys=True, allow_nan=False) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
