"""Fixed-jump-start causal frontier acquisition for trajectory-centered JIT.

A continuation-successful RSI state is not, by itself, jumping-capability
evidence. This module therefore generates every prospective Jump-Tube candidate
from the authoritative fixed ground jump-start reset and advances only through env.step.
RSI is reserved for the later continuation evaluation of a state that has
already been reached causally.

The nominal centerline supplies longitudinal target slices only. Source-Tube
states are never used as physical reset points in this acquisition mode. For a
target x slice, the frozen unified policy is rolled forward from the jump start and
a bounded action perturbation is activated within a predeclared causal lookback
window. The first physically valid state in the target 0.1 m slice is captured.

For downstream candidates the state must be post-Apex, descending, and still
pre-contact. Post-landing recovery cannot become Jump-Tube frontier evidence.
"""
from __future__ import annotations

from collections import Counter
import hashlib
import json
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

import jax
from jax import numpy as jp
import numpy as np

from ..constants import ACTION_ORDER
from ..unified_boundary import action_sparse_directions
from ..unified_envelope_snapshot import (
    capture_unified_envelope_snapshot,
    physical_state_sha256,
    snapshot_context_sha256,
    save_unified_envelope_snapshot,
)
from ..analysis.nominal_jump_centerline import load_nominal_jump_centerline


CATALOG_SCHEMA = "jit_unified_boundary_catalog_v1"
PROTOCOL_SCHEMA = "jit_jump_start_connected_causal_jump_acquisition_v1"
ACQUISITION_MODE = "jump_start_connected_causal_rollout_v1"
DEFAULT_LOOKBACKS_M = (0.1, 0.2, 0.3)
DEFAULT_MAX_FORWARD_TICKS = 400
TARGET_HALF_WIDTH_M = 0.05 + 1.0e-9
VARIANT_PARTITION_MODULUS = 5


def _canonical_sha256(value: Any) -> str:
    raw = json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _truth(value: Any) -> bool:
    return bool(np.asarray(jax.device_get(value)))


def _integer(value: Any) -> int:
    return int(np.asarray(jax.device_get(value)))


def _float(value: Any) -> float:
    return float(np.asarray(jax.device_get(value)))


def _finite_state(state: Any, action: Any | None = None) -> bool:
    arrays = (
        np.asarray(jax.device_get(state.data.qpos)),
        np.asarray(jax.device_get(state.data.qvel)),
        np.asarray(jax.device_get(state.obs["state"])),
    )
    if action is not None:
        arrays = (*arrays, np.asarray(jax.device_get(action)))
    return all(np.isfinite(value).all() for value in arrays)


def physical_state_sha256_from_state(state: Any) -> str:
    digest = hashlib.sha256()
    digest.update(
        np.ascontiguousarray(np.asarray(jax.device_get(state.data.qpos))).tobytes()
    )
    digest.update(
        np.ascontiguousarray(np.asarray(jax.device_get(state.data.qvel))).tobytes()
    )
    return digest.hexdigest()


def validate_jump_start_reachability_payload(payload: Mapping[str, Any]) -> None:
    if payload.get("schema") != "jit_jump_start_reachability_provenance_v1":
        raise ValueError("candidate has invalid jump-start reachability schema")
    if payload.get("jump_start_connected") is not True:
        raise ValueError("candidate lacks jump-start reachability")
    if payload.get("natural_start_connected") is not False:
        raise ValueError("jump-start candidate improperly claims natural-start connection")
    if payload.get("generated_by_env_step_only") is not True:
        raise ValueError("candidate reachability was not generated by env.step only")
    if payload.get("proposal_anchor_used_as_reset") is not False:
        raise ValueError("proposal anchor was improperly used as a physical reset")
    if payload.get("rsi_used_to_establish_reachability") is not False:
        raise ValueError("RSI cannot establish forward reachability")
    if payload.get("qpos_qvel_injection_used") is not False:
        raise ValueError("qpos/qvel injection cannot establish forward reachability")
    for field in (
        "jump_start_state_sha256",
        "perturbation_start_state_sha256",
    ):
        value = str(payload.get(field, ""))
        if len(value) != 64:
            raise ValueError(f"invalid jump-start reachability hash: {field}")
    if int(payload.get("environment_transitions_from_jump_start", -1)) <= 0:
        raise ValueError("jump-start reachability transition count must be positive")


def _semantic_candidate(state: Any, phase: str) -> bool:
    active = _integer(state.info["active_phase"])
    if phase == "upstream":
        return active == 0 and not _truth(state.info["up_events"].apex_seen)
    if phase != "downstream":
        return False
    if active != 1:
        return False
    if _float(state.data.qvel[2]) >= 0.0:
        return False
    if _truth(state.info["down_events"].valid_contact_seen):
        return False
    return True


def _normalize_snapshot_context(state: Any, phase: str) -> Any:
    """Normalize only administrative phase-transition bookkeeping for RSI labeling.

    The candidate qpos/qvel, FIFO, action history, up/down event state and active
    phase are untouched. Existing continuation validation historically requires
    a fresh phase_transitioned=False snapshot. Downstream continuation semantics
    do not depend on preserving that one administrative flag.
    """
    info = {**state.info, "phase_transitioned": jp.asarray(False)}
    metrics = {
        **state.metrics,
        "event/tube_phase_transition": jp.asarray(0.0, jp.float32),
    }
    return state.replace(info=info, metrics=metrics)


def _variant_specs(
    *,
    lookbacks_m: Sequence[float],
    strengths: Sequence[float],
    directions: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    ordinal = 0
    for lookback in lookbacks_m:
        for strength in strengths:
            for direction in directions:
                result.append(
                    {
                        "ordinal": ordinal,
                        "lookback_m": float(lookback),
                        "strength": float(strength),
                        "direction": dict(direction),
                    }
                )
                ordinal += 1
    return result


def collect_jump_start_connected_candidates(
    declared_anchors: Sequence[Mapping[str, Any]],
    output_dir: Path,
    *,
    env: Any,
    policy: Callable[[Any, Any], Any],
    policy_record: Mapping[str, Any],
    frozen_manifest_sha256: str,
    nominal_centerline: Path,
    protocol_seed: int,
    strengths: Sequence[float],
    action_names: Sequence[str],
    signs: Sequence[int],
    lookbacks_m: Sequence[float] = DEFAULT_LOOKBACKS_M,
    max_forward_ticks: int = DEFAULT_MAX_FORWARD_TICKS,
    evidence_mode: str = "legacy_training_support_novelty_v1",
    probe_bank_sha256: str | None = None,
    logical_role: str | None = None,
    start_contract_sha256: str | None = None,
    acquisition_interaction_ceiling: int | None = None,
) -> dict[str, Any]:
    """Generate unlabeled jump-start-connected candidates around centerline x slices."""
    if evidence_mode not in {"legacy_training_support_novelty_v1", "probe_bank_arrivals_v1"}:
        raise ValueError("unknown causal evidence mode")
    if evidence_mode == "probe_bank_arrivals_v1" and (not probe_bank_sha256 or len(probe_bank_sha256) != 64):
        raise ValueError("new arrival mode requires an immutable probe bank identity")
    if not declared_anchors:
        raise ValueError("causal Jump acquisition requires declared centerline-slice anchors")
    if int(max_forward_ticks) <= 0:
        raise ValueError("max_forward_ticks must be positive")
    if int(policy_record.get("iteration", -1)) < 0:
        raise ValueError("frozen unified policy iteration is invalid")
    if policy_record.get("policy_role") != "envelope_expansion_authority":
        raise ValueError("frozen unified policy is not an expansion authority")
    if policy_record.get("xml_sha256") != env._bundle.xml_sha256:
        raise ValueError("causal Jump policy/runtime XML mismatch")

    centerline = load_nominal_jump_centerline(Path(nominal_centerline))
    jump_start_expected = str(centerline["jump_start_state_sha256"])
    directions = action_sparse_directions(
        action_names=tuple(action_names),
        signs=tuple(int(v) for v in signs),
        active_action_dimensions=1,
    )
    lookbacks = tuple(float(value) for value in lookbacks_m)
    if not lookbacks or any(value <= 0.0 for value in lookbacks):
        raise ValueError("causal lookback distances must be positive")
    strength_values = tuple(float(value) for value in strengths)
    if not strength_values or any(value <= 0.0 for value in strength_values):
        raise ValueError("causal strengths must be positive")

    variants = _variant_specs(
        lookbacks_m=lookbacks,
        strengths=strength_values,
        directions=directions,
    )
    if not variants:
        raise ValueError("causal Jump acquisition generated no perturbation variants")

    artifact = env.tube_pool.artifact
    support_hashes = {str(row["state_sha256"]) for row in artifact.entries}
    maximum_interactions = (
        len(declared_anchors)
        * max(1, (len(variants) + VARIANT_PARTITION_MODULUS - 1) // VARIANT_PARTITION_MODULUS)
        * int(max_forward_ticks)
    )
    if acquisition_interaction_ceiling is not None and maximum_interactions > acquisition_interaction_ceiling:
        raise ValueError("acquisition exceeds declared interaction ceiling before rollout")
    if evidence_mode == "probe_bank_arrivals_v1" and (logical_role not in {"train", "calibration", "acceptance"} or not start_contract_sha256):
        raise ValueError("bank acquisition requires logical role and declared start contract")
    protocol = {
        "schema": PROTOCOL_SCHEMA,
        "status": "predeclared",
        "purpose": "jump_start_connected_forward_reachability_then_continuation_candidate_acquisition",
        "acquisition_mode": ACQUISITION_MODE,
        "iteration": int(policy_record["iteration"]),
        "policy_name": str(policy_record["name"]),
        "policy_actor_sha256": str(policy_record["actor_sha256"]),
        "policy_payload_sha256": str(policy_record["payload_sha256"]),
        "policy_formal_config_sha256": str(policy_record["formal_config_sha256"]),
        "frozen_unified_manifest_sha256": str(frozen_manifest_sha256),
        "source_tube_manifest_sha256": str(artifact.manifest["manifest_sha256"]),
        "nominal_centerline": str(nominal_centerline),
        "nominal_centerline_sha256": str(centerline["centerline_sha256"]),
        "jump_start_state_sha256": jump_start_expected,
        "natural_start_connected": False,
        "target_x_half_width_m": TARGET_HALF_WIDTH_M,
        "causal_lookbacks_m": list(lookbacks),
        "strengths": list(strength_values),
        "selected_action_names": list(action_names),
        "selected_signs": [int(v) for v in signs],
        "variant_partition_modulus": VARIANT_PARTITION_MODULUS,
        "max_forward_ticks_per_attempt": int(max_forward_ticks),
        "maximum_environment_interactions": int(maximum_interactions),
        "state_generation": (
            "authoritative fixed ground jump-start reset; deterministic frozen policy prefix; bounded action "
            "perturbation activated only inside a declared spatial lookback before target x; "
            "advance only by env.step; capture first semantically valid state in target 0.1 m slice"
        ),
        "reachability_definition": (
            "candidate is forward-reachable iff the saved acquisition trace began at the locked "
            "fixed jump-start state and reached the candidate using env.step only"
        ),
        "rsi_role": "continuation_evaluation_only_after_forward_reachability_is_established",
        "training_transitions": 0,
        "expert_switching_used": False,
        "test_data_used": False,
        "validation_data_used": False,
        "final_evaluation_data_used": False,
        "claim_boundary": {
            "unlabeled_acquisition_only": True,
            "tube_expansion_claim": False,
            "jce_jel_claim": False,
            "certified_safe_set_claim": False,
        },
    }
    if evidence_mode == "probe_bank_arrivals_v1":
        protocol.update(evidence_mode=evidence_mode, probe_bank_sha256=probe_bank_sha256,
                        logical_role=logical_role, start_contract_sha256=start_contract_sha256,
                        training_support_membership_excludes_arrival=False,
                        candidate_deduplication="snapshot_context_sha256")
    protocol_sha = _canonical_sha256(protocol)

    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=False)
    (output / "protocol.json").write_text(
        json.dumps(
            {**protocol, "protocol_sha256": protocol_sha},
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n",
        encoding="utf-8",
    )
    bank = output / "boundary_bank"
    (bank / "snapshots").mkdir(parents=True, exist_ok=False)

    reset_jump_start = jax.jit(env._reset_jump_start_unified)
    step = jax.jit(env.step)
    base_key = jax.random.PRNGKey(int(protocol_seed))
    entries: list[dict[str, Any]] = []
    seen_states: set[str] = set()
    exclusions = Counter()
    phase_attempted = Counter()
    phase_accepted = Counter()
    interactions = 0
    attempt_index = 0

    ordered_anchors = sorted(
        (dict(row) for row in declared_anchors),
        key=lambda row: (
            0 if str(row["phase"]) == "upstream" else 1,
            float(row["x_target_m"]),
            int(row["proposal_family_index"]),
            str(row["parent_group_id"]),
        ),
    )

    for anchor in ordered_anchors:
        phase = str(anchor["phase"])
        phase_index = 0 if phase == "upstream" else 1
        target_x = float(anchor["x_target_m"])
        family = int(anchor["proposal_family_index"])
        if family < 0 or family >= VARIANT_PARTITION_MODULUS:
            raise ValueError("proposal family index is outside the predeclared partition")
        if not float(centerline["x_min_m"]) - 1.0e-9 <= target_x <= float(
            centerline["effective_centerline_max_x_m"]
        ) + 1.0e-9:
            raise ValueError("causal target slice lies outside locked centerline corridor")

        for spec in variants:
            if int(spec["ordinal"]) % VARIANT_PARTITION_MODULUS != family:
                continue
            phase_attempted[phase] += 1
            attempt_index += 1
            variant_key = jax.random.fold_in(base_key, int(attempt_index))
            reset_key, policy_base_key = jax.random.split(variant_key)
            state = reset_jump_start(reset_key)
            jax.block_until_ready(state)
            if _truth(state.info["reset_from_soft_tube"]):
                raise ValueError("causal Jump acquisition unexpectedly started from Tube RSI")
            if not _truth(state.info["reset_from_jump_start"]):
                raise ValueError("causal Jump acquisition did not use the fixed jump start")
            if _truth(state.info["expert_switching_used"]):
                raise ValueError("causal Jump acquisition used expert switching")
            jump_start_sha = physical_state_sha256_from_state(state)
            if jump_start_sha != jump_start_expected:
                raise ValueError("causal jump start differs from the locked centerline start")

            direction = spec["direction"]
            lookback = float(spec["lookback_m"])
            strength = float(spec["strength"])
            perturb_start_x = target_x - lookback
            perturbation_started = False
            perturbation_start_sha = ""
            perturbation_start_actual_x = None
            nominal_prefix_ticks = 0
            perturbed_ticks = 0
            candidate_state = None
            rejected = None
            nominal_actions: list[list[float]] = []
            perturbed_actions: list[list[float]] = []
            effective_deltas: list[list[float]] = []

            for tick in range(int(max_forward_ticks)):
                if _truth(state.done):
                    rejected = "terminal_before_target"
                    break
                x_before = _float(state.data.qpos[0])
                if x_before > target_x + TARGET_HALF_WIDTH_M:
                    rejected = "missed_target_slice"
                    break

                action_key = jax.random.fold_in(policy_base_key, int(tick))
                result = policy(state.obs, action_key)
                nominal = result[0] if isinstance(result, tuple) else result
                nominal_array = np.asarray(
                    jax.device_get(nominal), dtype=np.float32
                ).reshape(-1)
                if nominal_array.shape != (len(ACTION_ORDER),) or not np.isfinite(
                    nominal_array
                ).all():
                    raise ValueError("frozen unified policy returned an invalid action")

                use_perturbation = x_before >= perturb_start_x - 1.0e-9
                if use_perturbation and not perturbation_started:
                    perturbation_started = True
                    perturbation_start_sha = physical_state_sha256_from_state(state)
                    perturbation_start_actual_x = x_before
                if use_perturbation:
                    requested = nominal_array + np.asarray(
                        direction["basis_vector"], dtype=np.float32
                    ) * np.float32(strength)
                    action = np.clip(requested, -1.0, 1.0).astype(np.float32)
                    perturbed_ticks += 1
                else:
                    action = nominal_array
                    nominal_prefix_ticks += 1

                state = step(state, action)
                jax.block_until_ready(state)
                interactions += 1
                nominal_actions.append(nominal_array.tolist())
                perturbed_actions.append(np.asarray(action, dtype=np.float32).tolist())
                effective_deltas.append((np.asarray(action) - nominal_array).tolist())

                if not _finite_state(state, action):
                    rejected = "nonfinite"
                    break
                if _truth(state.info["expert_switching_used"]):
                    raise ValueError("causal Jump acquisition used expert switching")

                x_after = _float(state.data.qpos[0])
                inside = abs(x_after - target_x) <= TARGET_HALF_WIDTH_M
                if inside and _semantic_candidate(state, phase):
                    candidate_state = state
                    break
                if x_after > target_x + TARGET_HALF_WIDTH_M:
                    rejected = "semantic_mismatch_or_slice_crossed"
                    break

            if candidate_state is None:
                exclusions[rejected or "forward_horizon_exhausted"] += 1
                continue
            if not perturbation_started or not perturbation_start_sha:
                exclusions["target_reached_before_perturbation_window"] += 1
                continue

            normalized_state = (candidate_state if evidence_mode == "probe_bank_arrivals_v1"
                                else _normalize_snapshot_context(candidate_state, phase))
            jump_start_reachability = {
                "schema": "jit_jump_start_reachability_provenance_v1",
                "jump_start_connected": True,
                "natural_start_connected": False,
                "jump_start_state_sha256": jump_start_sha,
                "generated_by_env_step_only": True,
                "rsi_used_to_establish_reachability": False,
                "qpos_qvel_injection_used": False,
                "proposal_anchor_used_as_reset": False,
                "proposal_anchor_state_sha256": str(anchor["state_sha256"]),
                "proposal_parent_group_id": str(anchor["parent_group_id"]),
                "target_x_m": target_x,
                "lookback_m": lookback,
                "perturbation_start_target_x_m": perturb_start_x,
                "perturbation_start_actual_x_m": float(perturbation_start_actual_x),
                "perturbation_start_state_sha256": perturbation_start_sha,
                "environment_transitions_before_perturbation": int(nominal_prefix_ticks),
                "perturbed_environment_transitions": int(perturbed_ticks),
                "environment_transitions_from_jump_start": int(
                    nominal_prefix_ticks + perturbed_ticks
                ),
                "proposal_family_index": family,
                "variant_ordinal": int(spec["ordinal"]),
            }
            validate_jump_start_reachability_payload(jump_start_reachability)
            jump_start_reachability["reachability_sha256"] = _canonical_sha256(
                jump_start_reachability
            )

            snapshot = capture_unified_envelope_snapshot(
                normalized_state,
                env=env,
                parent_trajectory=str(anchor["parent_group_id"]),
                parent_state_sha256=perturbation_start_sha,
                config_sha256=str(policy_record["formal_config_sha256"]),
                policy_actor_sha256=str(policy_record["actor_sha256"]),
                policy_payload_sha256=str(policy_record["payload_sha256"]),
                policy_iteration=int(policy_record["iteration"]),
            )
            state_hash = physical_state_sha256(snapshot)
            context_hash = snapshot_context_sha256(snapshot)
            if evidence_mode == "legacy_training_support_novelty_v1" and state_hash in support_hashes:
                exclusions["existing_control_tube_state"] += 1
                continue
            evidence_key = context_hash if evidence_mode == "probe_bank_arrivals_v1" else state_hash
            if evidence_key in seen_states:
                exclusions["duplicate_candidate_state"] += 1
                continue
            seen_states.add(evidence_key)

            relative = Path("snapshots") / f"candidate_{len(entries):06d}"
            save_unified_envelope_snapshot(bank / relative, snapshot)
            qpos = np.asarray(snapshot.qpos)
            qvel = np.asarray(snapshot.qvel)
            entries.append(
                {
                    "candidate_id": (
                        f"pi{policy_record['iteration']}_causal_{phase}_{len(entries):06d}"
                    ),
                    # Keep the historical candidate kind so the frozen continuation
                    # labeler remains backward-compatible. Jump-start reachability is
                    # carried by the explicit provenance object below.
                    "candidate_kind": "reachable_unified_frontier_probe",
                    "acquisition_mode": ACQUISITION_MODE,
                    "split": "train",
                    "phase": phase,
                    "phase_index": phase_index,
                    "snapshot": str(relative),
                    "source_bank": "boundary_bank",
                    "state_sha256": state_hash,
                    **({"snapshot_context_sha256": context_hash,
                        "probe_bank_sha256": probe_bank_sha256,
                        "already_in_training_support": state_hash in support_hashes}
                       if evidence_mode == "probe_bank_arrivals_v1" else {}),
                    "parent_group_id": str(anchor["parent_group_id"]),
                    "parent_state_sha256": perturbation_start_sha,
                    "proposal_anchor_state_sha256": str(anchor["state_sha256"]),
                    "proposal_family_index": family,
                    "x_target_m": target_x,
                    "policy_iteration": int(policy_record["iteration"]),
                    "policy_actor_sha256": str(policy_record["actor_sha256"]),
                    "policy_payload_sha256": str(policy_record["payload_sha256"]),
                    "protocol_sha256": protocol_sha,
                    "jump_start_reachability": jump_start_reachability,
                    "perturbation": {
                        **direction,
                        "strength": strength,
                        "lookback_m": lookback,
                        "variant_ordinal": int(spec["ordinal"]),
                        "nominal_actions": nominal_actions,
                        "perturbed_actions": perturbed_actions,
                        "effective_deltas": effective_deltas,
                    },
                    "episode_step": snapshot.episode_step,
                    "phase_episode_step": snapshot.phase_episode_step,
                    "x": float(qpos[0]),
                    "z": float(qpos[2]),
                    "vx": float(qvel[0]),
                    "vz": float(qvel[2]),
                }
            )
            phase_accepted[phase] += 1

    if interactions > maximum_interactions:
        raise ValueError("causal Jump acquisition exceeded predeclared interaction ceiling")
    report = {
        "schema": CATALOG_SCHEMA,
        "status": "completed",
        "artifact_role": "unlabeled_policy_conditioned_frontier_candidates",
        "split": "train",
        "iteration": int(policy_record["iteration"]),
        "policy_name": str(policy_record["name"]),
        "policy_actor_sha256": str(policy_record["actor_sha256"]),
        "policy_payload_sha256": str(policy_record["payload_sha256"]),
        "frozen_unified_manifest_sha256": str(frozen_manifest_sha256),
        "source_tube_manifest_sha256": str(artifact.manifest["manifest_sha256"]),
        "protocol_sha256": protocol_sha,
        "acquisition_mode": ACQUISITION_MODE,
        "jump_start_reachability_proven": True,
        "natural_start_connected": False,
        "rsi_used_for_reachability": False,
        "jump_start_state_sha256": jump_start_expected,
        "attempted_candidate_count": int(sum(phase_attempted.values())),
        "candidate_count": len(entries),
        "phase_attempted_candidate_counts": {
            phase: int(phase_attempted[phase])
            for phase in ("upstream", "downstream")
        },
        "phase_candidate_counts": {
            phase: int(phase_accepted[phase])
            for phase in ("upstream", "downstream")
        },
        "environment_interactions": int(interactions),
        "maximum_environment_interactions": int(maximum_interactions),
        "exclusion_counts": dict(sorted(exclusions.items())),
        "training_transitions": 0,
        "expert_switching_used": False,
        "test_data_used": False,
        "validation_data_used": False,
        "final_evaluation_data_used": False,
        "claim_boundary": {
            "unlabeled_acquisition_only": True,
            "tube_expansion_claim": False,
            "jce_jel_claim": False,
            "certified_safe_set_claim": False,
        },
        "entries": entries,
    }
    (output / "catalog.json").write_text(
        json.dumps(report, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    summary = {key: value for key, value in report.items() if key != "entries"}
    (output / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return report
