"""Fixed-jump-start causal frontier acquisition for trajectory-centered JIT.

A continuation-successful RSI state is not, by itself, jumping-capability
evidence. This module therefore generates every prospective Jump-Tube candidate
from the authoritative fixed ground jump-start reset and advances only through env.step.
RSI is reserved for the later continuation evaluation of a state that has
already been reached causally.

The nominal centerline supplies longitudinal target slices only. Source-Tube
states are never used as physical reset points in this acquisition mode. For a
target x slice, the frozen unified policy is rolled forward from the jump start and
a bounded action perturbation is activated within a predeclared causal lookback
window. The first physically valid state in the target 0.1 m slice is captured.

For downstream candidates the state must be post-Apex, descending, and still
pre-contact. Post-landing recovery cannot become Jump-Tube frontier evidence.
"""
from __future__ import annotations

from collections import Counter
import hashlib
import json
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

import jax
from jax import numpy as jp
import numpy as np

from ..constants import ACTION_ORDER
from ..unified_boundary import action_sparse_directions
from ..unified_envelope_snapshot import (
    capture_unified_envelope_snapshot,
    physical_state_sha256,
    snapshot_context_sha256,
    save_unified_envelope_snapshot,
)
from ..analysis.nominal_jump_centerline import load_nominal_jump_centerline


CATALOG_SCHEMA = "jit_unified_boundary_catalog_v1"
PROTOCOL_SCHEMA = "jit_jump_start_connected_causal_jump_acquisition_v1"
ACQUISITION_MODE = "jump_start_connected_causal_rollout_v1"
DEFAULT_LOOKBACKS_M = (0.1, 0.2, 0.3)
DEFAULT_MAX_FORWARD_TICKS = 400
TARGET_HALF_WIDTH_M = 0.05 + 1.0e-9
VARIANT_PARTITION_MODULUS = 5


def _canonical_sha256(value: Any) -> str:
    raw = json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _truth(value: Any) -> bool:
    return bool(np.asarray(jax.device_get(value)))


def _integer(value: Any) -> int:
    return int(np.asarray(jax.device_get(value)))


def _float(value: Any) -> float:
    return float(np.asarray(jax.device_get(value)))


def _finite_state(state: Any, action: Any | None = None) -> bool:
    arrays = (
        np.asarray(jax.device_get(state.data.qpos)),
        np.asarray(jax.device_get(state.data.qvel)),
        np.asarray(jax.device_get(state.obs["state"])),
    )
    if action is not None:
        arrays = (*arrays, np.asarray(jax.device_get(action)))
    return all(np.isfinite(value).all() for value in arrays)


def physical_state_sha256_from_state(state: Any) -> str:
    digest = hashlib.sha256()
    digest.update(
        np.ascontiguousarray(np.asarray(jax.device_get(state.data.qpos))).tobytes()
    )
    digest.update(
        np.ascontiguousarray(np.asarray(jax.device_get(state.data.qvel))).tobytes()
    )
    return digest.hexdigest()


def validate_jump_start_reachability_payload(payload: Mapping[str, Any]) -> None:
    if payload.get("schema") != "jit_jump_start_reachability_provenance_v1":
        raise ValueError("candidate has invalid jump-start reachability schema")
    if payload.get("jump_start_connected") is not True:
        raise ValueError("candidate lacks jump-start reachability")
    if payload.get("natural_start_connected") is not False:
        raise ValueError("jump-start candidate improperly claims natural-start connection")
    if payload.get("generated_by_env_step_only") is not True:
        raise ValueError("candidate reachability was not generated by env.step only")
    if payload.get("proposal_anchor_used_as_reset") is not False:
        raise ValueError("proposal anchor was improperly used as a physical reset")
    if payload.get("rsi_used_to_establish_reachability") is not False:
        raise ValueError("RSI cannot establish forward reachability")
    if payload.get("qpos_qvel_injection_used") is not False:
        raise ValueError("qpos/qvel injection cannot establish forward reachability")
    for field in (
        "jump_start_state_sha256",
        "perturbation_start_state_sha256",
    ):
        value = str(payload.get(field, ""))
        if len(value) != 64:
            raise ValueError(f"invalid jump-start reachability hash: {field}")
    if int(payload.get("environment_transitions_from_jump_start", -1)) <= 0:
        raise ValueError("jump-start reachability transition count must be positive")


def _semantic_candidate(state: Any, phase: str) -> bool:
    active = _integer(state.info["active_phase"])
    if phase == "upstream":
        return active == 0 and not _truth(state.info["up_events"].apex_seen)
    if phase != "downstream":
        return False
    if active != 1:
        return False
    if _float(state.data.qvel[2]) >= 0.0:
        return False
    if _truth(state.info["down_events"].valid_contact_seen):
        return False
    return True


def _normalize_snapshot_context(state: Any, phase: str) -> Any:
    """Normalize only administrative phase-transition bookkeeping for RSI labeling.

    The candidate qpos/qvel, FIFO, action history, up/down event state and active
    phase are untouched. Existing continuation validation historically requires
    a fresh phase_transitioned=False snapshot. Downstream continuation semantics
    do not depend on preserving that one administrative flag.
    """
    info = {**state.info, "phase_transitioned": jp.asarray(False)}
    metrics = {
        **state.metrics,
        "event/tube_phase_transition": jp.asarray(0.0, jp.float32),
    }
    return state.replace(info=info, metrics=metrics)


def _variant_specs(
    *,
    lookbacks_m: Sequence[float],
    strengths: Sequence[float],
    directions: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    ordinal = 0
    for lookback in lookbacks_m:
        for strength in strengths:
            for direction in directions:
                result.append(
                    {
                        "ordinal": ordinal,
                        "lookback_m": float(lookback),
                        "strength": float(strength),
                        "direction": dict(direction),
                    }
                )
                ordinal += 1
    return result


def validate_acquisition_policy_role(policy_record, *, evidence_mode, logical_role):
    if int(policy_record.get("iteration", -1)) < 0:
        raise ValueError("frozen unified policy iteration is invalid")
    role = policy_record.get("policy_role")
    if role == "envelope_expansion_authority":
        return
    if (role == "development_checkpoint" and policy_record.get("data_role") == "train"
        and evidence_mode == "probe_bank_arrivals_v1" and logical_role == "train"):
        return
    raise ValueError("policy requires expansion authority or explicit TRAIN development probe")


def _residual_action(artifact, observation, nominal, goal, state, active):
    """Shared spatial gate; history advances even when the residual is disabled.

    Acquisition requires slew >= 2 * amplitude, so setting delta to zero at the
    spatial gate obeys the declared slew bound without an exception.
    """
    from ..residual_exploration import apply_residual, ExplorerState
    if active:
        return apply_residual(artifact['variables'], artifact['contract'],
                              observation, nominal, goal, state)
    history = state.history
    if artifact['contract']['history_steps']:
        history = jp.concatenate([history[1:], jp.asarray(observation)[None, :]])
    return nominal, ExplorerState(history, jp.zeros(4))


def _explorer_state_record(state):
    return {'history': np.asarray(jax.device_get(state.history)).tolist(),
            'previous_delta': np.asarray(jax.device_get(state.previous_delta)).tolist()}


def collect_jump_start_connected_candidates(
    declared_anchors: Sequence[Mapping[str, Any]],
    output_dir: Path,
    *,
    env: Any,
    policy: Callable[[Any, Any], Any],
    policy_record: Mapping[str, Any],
    frozen_manifest_sha256: str,
    nominal_centerline: Path,
    protocol_seed: int,
    strengths: Sequence[float],
    action_names: Sequence[str],
    signs: Sequence[int],
    lookbacks_m: Sequence[float] = DEFAULT_LOOKBACKS_M,
    max_forward_ticks: int = DEFAULT_MAX_FORWARD_TICKS,
    evidence_mode: str = "legacy_training_support_novelty_v1",
    probe_bank_sha256: str | None = None,
    logical_role: str | None = None,
    start_contract_sha256: str | None = None,
    acquisition_interaction_ceiling: int | None = None,
    sampling_mode: str = "single_target_v1",
    slice_spacing_m: float = 0.05,
    max_candidates_per_attempt: int = 64,
    sampling_max_x_m: float | None = None,
    record_action_tape: bool = False,
    residual_explorer: Path | None = None,
) -> dict[str, Any]:
    """Generate unlabeled jump-start-connected candidates around centerline x slices."""
    if not isinstance(record_action_tape, bool):
        raise ValueError("record_action_tape must be boolean")
    if (record_action_tape or residual_explorer is not None) and (
            not record_action_tape or sampling_mode != "trajectory_slices_v2" or logical_role != "train"):
        raise ValueError("action tape/residual acquisition requires full recording and dense TRAIN mode")
    if sampling_mode not in {"single_target_v1", "trajectory_slices_v2"}:
        raise ValueError("unknown trajectory sampling mode")
    dense = sampling_mode == "trajectory_slices_v2"
    if dense and (evidence_mode != "probe_bank_arrivals_v1" or not 0.01 <= slice_spacing_m <= 0.1
                  or not 1 <= max_candidates_per_attempt <= 128):
        raise ValueError("dense sampling needs bank context, spacing 0.01..0.1 and bounded candidates")
    if evidence_mode not in {"legacy_training_support_novelty_v1", "probe_bank_arrivals_v1"}:
        raise ValueError("unknown causal evidence mode")
    if evidence_mode == "probe_bank_arrivals_v1" and (not probe_bank_sha256 or len(probe_bank_sha256) != 64):
        raise ValueError("new arrival mode requires an immutable probe bank identity")
    if not declared_anchors:
        raise ValueError("causal Jump acquisition requires declared centerline-slice anchors")
    if int(max_forward_ticks) <= 0:
        raise ValueError("max_forward_ticks must be positive")
    validate_acquisition_policy_role(policy_record, evidence_mode=evidence_mode, logical_role=logical_role)
    if policy_record.get("xml_sha256") != env._bundle.xml_sha256:
        raise ValueError("causal Jump policy/runtime XML mismatch")

    explorer = None
    if residual_explorer is not None:
        from ..residual_exploration import load_artifact, file_sha, reset_state
        from ..action_tape import GOAL_NAMES
        from ..constants import CTRL_DT
        explorer = load_artifact(Path(residual_explorer))
        contract = explorer['contract']
        if frozen_manifest_sha256 not in {r['sha256'] for r in explorer['frozen_base_bank']}:
            raise ValueError("residual explorer has unknown frozen base manifest")
        if (contract['model_sha256'] != env._bundle.xml_sha256 or
                contract['action_names'] != list(ACTION_ORDER) or contract['goal_names'] != GOAL_NAMES or
                contract['control_dt'] != CTRL_DT or
                contract.get('goal_contract') != 'exogenous fixed perturbation schedule; no future outcome features'):
            raise ValueError("residual explorer model/action/goal/timing contract mismatch")
        from ..residual_exploration import digest
        source_root = Path(__file__).resolve().parents[1]
        if contract['observation_contract_sha256'] != digest({name:file_sha(source_root/name) for name in ('observation.py','constants.py')}):
            raise ValueError("residual explorer observation source contract mismatch")
        if (contract['action_low'] != [-1.]*4 or contract['action_high'] != [1.]*4 or
                np.any(np.asarray(contract['slew_limit']) < 2*np.asarray(contract['delta_limit']))):
            raise ValueError("residual spatial gate requires canonical action bounds and slew >= 2 * delta_limit")

    centerline = load_nominal_jump_centerline(Path(nominal_centerline))
    original_x_max = float(centerline["effective_centerline_max_x_m"])
    sample_x_max = original_x_max if sampling_max_x_m is None else float(sampling_max_x_m)
    if sampling_max_x_m is not None and (not dense or not np.isfinite(sample_x_max) or not original_x_max <= sample_x_max <= 8.):
        raise ValueError("extended sampling requires dense mode and a finite declared guard up to 8 m")
    jump_start_expected = str(centerline["jump_start_state_sha256"])
    directions = action_sparse_directions(
        action_names=tuple(action_names),
        signs=tuple(int(v) for v in signs),
        active_action_dimensions=1,
    )
    lookbacks = tuple(float(value) for value in lookbacks_m)
    if not lookbacks or any(value <= 0.0 for value in lookbacks):
        raise ValueError("causal lookback distances must be positive")
    strength_values = tuple(float(value) for value in strengths)
    if not strength_values or any(value <= 0.0 for value in strength_values):
        raise ValueError("causal strengths must be positive")

    variants = _variant_specs(
        lookbacks_m=lookbacks,
        strengths=strength_values,
        directions=directions,
    )
    if not variants:
        raise ValueError("causal Jump acquisition generated no perturbation variants")

    artifact = env.tube_pool.artifact
    support_hashes = {str(row["state_sha256"]) for row in artifact.entries}
    maximum_interactions = (
        len(declared_anchors)
        * max(1, (len(variants) + VARIANT_PARTITION_MODULUS - 1) // VARIANT_PARTITION_MODULUS)
        * int(max_forward_ticks)
    )
    if acquisition_interaction_ceiling is not None and maximum_interactions > acquisition_interaction_ceiling:
        raise ValueError("acquisition exceeds declared interaction ceiling before rollout")
    if evidence_mode == "probe_bank_arrivals_v1" and (logical_role not in {"train", "calibration", "acceptance"} or not start_contract_sha256):
        raise ValueError("bank acquisition requires logical role and declared start contract")
    protocol = {
        "schema": PROTOCOL_SCHEMA,
        "status": "predeclared",
        "purpose": "jump_start_connected_forward_reachability_then_continuation_candidate_acquisition",
        "acquisition_mode": ACQUISITION_MODE,
        "iteration": int(policy_record["iteration"]),
        "policy_name": str(policy_record["name"]),
        "policy_actor_sha256": str(policy_record["actor_sha256"]),
        "policy_payload_sha256": str(policy_record["payload_sha256"]),
        "policy_formal_config_sha256": str(policy_record["formal_config_sha256"]),
        "frozen_unified_manifest_sha256": str(frozen_manifest_sha256),
        "source_tube_manifest_sha256": str(artifact.manifest["manifest_sha256"]),
        "nominal_centerline": str(nominal_centerline),
        "nominal_centerline_sha256": str(centerline["centerline_sha256"]),
        "jump_start_state_sha256": jump_start_expected,
        "natural_start_connected": False,
        "target_x_half_width_m": TARGET_HALF_WIDTH_M,
        "causal_lookbacks_m": list(lookbacks),
        "strengths": list(strength_values),
        "selected_action_names": list(action_names),
        "selected_signs": [int(v) for v in signs],
        "variant_partition_modulus": VARIANT_PARTITION_MODULUS,
        "max_forward_ticks_per_attempt": int(max_forward_ticks),
        "maximum_environment_interactions": int(maximum_interactions),
        "state_generation": (
            "authoritative fixed ground jump-start reset; deterministic frozen policy prefix; bounded action "
            "perturbation activated only inside a declared spatial lookback before target x; "
            "advance only by env.step; capture first semantically valid state in target 0.1 m slice"
        ),
        "reachability_definition": (
            "candidate is forward-reachable iff the saved acquisition trace began at the locked "
            "fixed jump-start state and reached the candidate using env.step only"
        ),
        "rsi_role": "continuation_evaluation_only_after_forward_reachability_is_established",
        "training_transitions": 0,
        "expert_switching_used": False,
        "test_data_used": False,
        "validation_data_used": False,
        "final_evaluation_data_used": False,
        "claim_boundary": {
            "unlabeled_acquisition_only": True,
            "tube_expansion_claim": False,
            "jce_jel_claim": False,
            "certified_safe_set_claim": False,
        },
    }
    if evidence_mode == "probe_bank_arrivals_v1":
        protocol.update(evidence_mode=evidence_mode, probe_bank_sha256=probe_bank_sha256,
                        logical_role=logical_role, start_contract_sha256=start_contract_sha256,
                        training_support_membership_excludes_arrival=False,
                        candidate_deduplication="snapshot_context_sha256")
    if dense:
        protocol.update(sampling_mode=sampling_mode, slice_spacing_m=slice_spacing_m,
                        target_x_half_width_m=slice_spacing_m / 2,
                        max_candidates_per_attempt=max_candidates_per_attempt,
                        state_generation="fixed-start env.step trajectory; first actual prelanding frame per phase/nearest x bin after perturbation onset; no interpolation",
                        perturbation_end="first x at or beyond anchor target; normal policy thereafter",
                        skipped_bins_are_not_filled=True,
                        shared_trajectory_frames_are_independent_samples=False)
    if sampling_max_x_m is not None:
        protocol.update(sampling_max_x_m=sample_x_max, original_centerline_max_x_m=original_x_max,
                        sampling_scope="real rollout until first landing/failure or declared guard; original reference unchanged")
    if record_action_tape:
        protocol.update(action_tape_anchors=[dict(anchor) for anchor in declared_anchors],
                        record_action_tape=True, action_tape_schema="jit_causal_action_tape_v1",
                        controller_mode="frozen_residual_spatial_window_v1" if explorer else "fixed_perturbation_v1")
    if explorer is not None:
        protocol.update(residual_explorer={'path':str(Path(residual_explorer).resolve()),
            'sha256':file_sha(residual_explorer), 'explorer_sha256':explorer['explorer_sha256']},
            residual_gate="shared fixed spatial window; history advances each tick; zero delta outside; slew >= twice amplitude")
    if record_action_tape:
        from ..action_tape import expected_action_tape_schedule
        expected_action_tape_schedule(protocol)
    protocol_sha = _canonical_sha256(protocol)

    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=False)
    (output / "protocol.json").write_text(
        json.dumps(
            {**protocol, "protocol_sha256": protocol_sha},
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
        + "\n",
        encoding="utf-8",
    )
    bank = output / "boundary_bank"
    (bank / "snapshots").mkdir(parents=True, exist_ok=False)

    reset_jump_start = jax.jit(env._reset_jump_start_unified)
    if dense:
        from ..frontier_label_shard_runner import _build_memory_stable_step
        step = _build_memory_stable_step(env)
    else:
        step = jax.jit(env.step)
    base_key = jax.random.PRNGKey(int(protocol_seed))
    entries: list[dict[str, Any]] = []
    seen_states: set[str] = set()
    exclusions = Counter()
    phase_attempted = Counter()
    phase_accepted = Counter()
    interactions = 0
    attempt_index = 0
    trajectory_receipts = []

    ordered_anchors = sorted(
        (dict(row) for row in declared_anchors),
        key=lambda row: (
            0 if str(row["phase"]) == "upstream" else 1,
            float(row["x_target_m"]),
            int(row["proposal_family_index"]),
            str(row["parent_group_id"]),
        ),
    )

    for anchor in ordered_anchors:
        phase = str(anchor["phase"])
        phase_index = 0 if phase == "upstream" else 1
        target_x = float(anchor["x_target_m"])
        family = int(anchor["proposal_family_index"])
        if family < 0 or family >= VARIANT_PARTITION_MODULUS:
            raise ValueError("proposal family index is outside the predeclared partition")
        if not float(centerline["x_min_m"]) - 1.0e-9 <= target_x <= float(
            centerline["effective_centerline_max_x_m"]
        ) + 1.0e-9:
            raise ValueError("causal target slice lies outside locked centerline corridor")

        for spec in variants:
            if int(spec["ordinal"]) % VARIANT_PARTITION_MODULUS != family:
                continue
            phase_attempted[phase] += 1
            attempt_index += 1
            variant_key = jax.random.fold_in(base_key, int(attempt_index))
            reset_key, policy_base_key = jax.random.split(variant_key)
            state = reset_jump_start(reset_key)
            jax.block_until_ready(state)
            if _truth(state.info["reset_from_soft_tube"]):
                raise ValueError("causal Jump acquisition unexpectedly started from Tube RSI")
            if not _truth(state.info["reset_from_jump_start"]):
                raise ValueError("causal Jump acquisition did not use the fixed jump start")
            if _truth(state.info["expert_switching_used"]):
                raise ValueError("causal Jump acquisition used expert switching")
            peak_root_z_m = _float(state.data.qpos[2])
            jump_start_sha = physical_state_sha256_from_state(state)
            if jump_start_sha != jump_start_expected:
                raise ValueError("causal jump start differs from the locked centerline start")

            direction = spec["direction"]
            lookback = float(spec["lookback_m"])
            strength = float(spec["strength"])
            perturb_start_x = target_x - lookback
            perturbation_started = False
            perturbation_ended = False
            perturbation_start_sha = ""
            perturbation_start_actual_x = None
            nominal_prefix_ticks = 0
            perturbed_ticks = 0
            perturbation_start_tick = 0
            candidate_state = None
            rejected = None
            nominal_actions: list[list[float]] = []
            perturbed_actions: list[list[float]] = []
            effective_deltas: list[list[float]] = []

            trajectory_id = f"{anchor['parent_group_id']}/variant_{spec['ordinal']}"
            tape_records = []
            previous_requested = np.zeros(4, dtype=np.float32)
            goal = [target_x, perturb_start_x, *direction['basis_vector'], strength]
            explorer_state = reset_state(explorer['contract']) if explorer else None

            def tape_identity(current):
                # Terminal marker is not part of snapshot context identity. Capture
                # final physical/controller context without changing rollout state.
                captured = capture_unified_envelope_snapshot(
                    current.replace(done=jp.asarray(False)) if _truth(current.done) else current,
                    env=env, parent_trajectory=trajectory_id, parent_state_sha256=jump_start_sha,
                    config_sha256=str(policy_record['formal_config_sha256']),
                    policy_actor_sha256=str(policy_record['actor_sha256']),
                    policy_payload_sha256=str(policy_record['payload_sha256']),
                    policy_iteration=int(policy_record['iteration']))
                return physical_state_sha256(captured), snapshot_context_sha256(captured), captured.episode_step

            initial_identity = tape_identity(state) if record_action_tape else None
            captured_bins = set()
            saved_this_attempt = 0
            attempt_start_interactions = interactions
            stop_reason = "forward_horizon_exhausted"

            def store_candidate(candidate_state, phase, target_x):
                phase_index = 0 if phase == "upstream" else 1
                normalized_state = (candidate_state if evidence_mode == "probe_bank_arrivals_v1"
                                    else _normalize_snapshot_context(candidate_state, phase))
                jump_start_reachability = {
                    "schema": "jit_jump_start_reachability_provenance_v1",
                    "jump_start_connected": True,
                    "natural_start_connected": False,
                    "jump_start_state_sha256": jump_start_sha,
                    "generated_by_env_step_only": True,
                    "rsi_used_to_establish_reachability": False,
                    "qpos_qvel_injection_used": False,
                    "proposal_anchor_used_as_reset": False,
                    "proposal_anchor_state_sha256": str(anchor["state_sha256"]),
                    "proposal_parent_group_id": str(anchor["parent_group_id"]),
                    "target_x_m": target_x,
                    "lookback_m": lookback,
                    "perturbation_start_target_x_m": perturb_start_x,
                    "perturbation_start_actual_x_m": float(perturbation_start_actual_x),
                    "perturbation_start_state_sha256": perturbation_start_sha,
                    "environment_transitions_before_perturbation": int(perturbation_start_tick if dense else nominal_prefix_ticks),
                    "perturbed_environment_transitions": int(perturbed_ticks),
                    "environment_transitions_from_jump_start": int(
                        nominal_prefix_ticks + perturbed_ticks
                    ),
                    "proposal_family_index": family,
                    "variant_ordinal": int(spec["ordinal"]),
                }
                if dense:
                    jump_start_reachability.update(trajectory_id=trajectory_id,
                        perturbation_anchor_x_m=float(anchor["x_target_m"]),
                        unperturbed_suffix_transitions=tick + 1 - perturbation_start_tick - perturbed_ticks)
                validate_jump_start_reachability_payload(jump_start_reachability)
                jump_start_reachability["reachability_sha256"] = _canonical_sha256(
                    jump_start_reachability
                )

                snapshot = capture_unified_envelope_snapshot(
                    normalized_state,
                    env=env,
                    parent_trajectory=str(anchor["parent_group_id"]),
                    parent_state_sha256=perturbation_start_sha,
                    config_sha256=str(policy_record["formal_config_sha256"]),
                    policy_actor_sha256=str(policy_record["actor_sha256"]),
                    policy_payload_sha256=str(policy_record["payload_sha256"]),
                    policy_iteration=int(policy_record["iteration"]),
                )
                state_hash = physical_state_sha256(snapshot)
                context_hash = snapshot_context_sha256(snapshot)
                if evidence_mode == "legacy_training_support_novelty_v1" and state_hash in support_hashes:
                    exclusions["existing_control_tube_state"] += 1
                    return False
                evidence_key = context_hash if evidence_mode == "probe_bank_arrivals_v1" else state_hash
                if evidence_key in seen_states:
                    exclusions["duplicate_candidate_state"] += 1
                    return False
                seen_states.add(evidence_key)

                relative = Path("snapshots") / f"candidate_{len(entries):06d}"
                save_unified_envelope_snapshot(bank / relative, snapshot)
                qpos = np.asarray(snapshot.qpos)
                qvel = np.asarray(snapshot.qvel)
                entries.append(
                    {
                        "candidate_id": (
                            f"pi{policy_record['iteration']}_causal_{phase}_{len(entries):06d}"
                        ),
                        # Keep the historical candidate kind so the frozen continuation
                        # labeler remains backward-compatible. Jump-start reachability is
                        # carried by the explicit provenance object below.
                        "candidate_kind": "reachable_unified_frontier_probe",
                        "acquisition_mode": ACQUISITION_MODE,
                        "split": "train",
                        "phase": phase,
                        "phase_index": phase_index,
                        "snapshot": str(relative),
                        "source_bank": "boundary_bank",
                        "state_sha256": state_hash,
                        **({"snapshot_context_sha256": context_hash,
                            "probe_bank_sha256": probe_bank_sha256,
                            "already_in_training_support": state_hash in support_hashes}
                           if evidence_mode == "probe_bank_arrivals_v1" else {}),
                        "parent_group_id": str(anchor["parent_group_id"]),
                        "parent_state_sha256": perturbation_start_sha,
                        "proposal_anchor_state_sha256": str(anchor["state_sha256"]),
                        "proposal_family_index": family,
                        "x_target_m": target_x,
                        "policy_iteration": int(policy_record["iteration"]),
                        "policy_actor_sha256": str(policy_record["actor_sha256"]),
                        "policy_payload_sha256": str(policy_record["payload_sha256"]),
                        "protocol_sha256": protocol_sha,
                        "jump_start_reachability": jump_start_reachability,
                        "perturbation": {
                            **direction,
                            "strength": strength,
                            "lookback_m": lookback,
                            "variant_ordinal": int(spec["ordinal"]),
                            "nominal_actions": list(nominal_actions),
                            "perturbed_actions": list(perturbed_actions),
                            "effective_deltas": list(effective_deltas),
                        },
                        "episode_step": snapshot.episode_step,
                        "phase_episode_step": snapshot.phase_episode_step,
                        "x": float(qpos[0]),
                        "z": float(qpos[2]),
                        "vx": float(qvel[0]),
                        "vz": float(qvel[2]),
                    }
                )
                phase_accepted[phase] += 1
                if dense:
                    entries[-1].update(trajectory_id=trajectory_id, trajectory_step=tick + 1,
                                       x_slice_spacing_m=slice_spacing_m, sampling_mode=sampling_mode)
                return True

            for tick in range(int(max_forward_ticks)):
                if _truth(state.done):
                    rejected = "terminal_before_target"
                    stop_reason = rejected
                    break
                x_before = _float(state.data.qpos[0])
                if not dense and x_before > target_x + TARGET_HALF_WIDTH_M:
                    rejected = "missed_target_slice"
                    break

                action_key = jax.random.fold_in(policy_base_key, int(tick))
                result = policy(state.obs, action_key)
                nominal = result[0] if isinstance(result, tuple) else result
                nominal_array = np.asarray(
                    jax.device_get(nominal), dtype=np.float32
                ).reshape(-1)
                if nominal_array.shape != (len(ACTION_ORDER),) or not np.isfinite(
                    nominal_array
                ).all():
                    raise ValueError("frozen unified policy returned an invalid action")

                if dense and perturbation_started and x_before >= target_x:
                    perturbation_ended = True
                use_perturbation = x_before >= perturb_start_x - 1.0e-9 and (not dense or (x_before < target_x and not perturbation_ended))
                if use_perturbation and not perturbation_started:
                    perturbation_started = True
                    perturbation_start_sha = physical_state_sha256_from_state(state)
                    perturbation_start_actual_x = x_before
                    perturbation_start_tick = tick
                if use_perturbation:
                    requested = nominal_array + np.asarray(
                        direction["basis_vector"], dtype=np.float32
                    ) * np.float32(strength)
                    action = np.clip(requested, -1.0, 1.0).astype(np.float32)
                    perturbed_ticks += 1
                else:
                    action = nominal_array
                    nominal_prefix_ticks += 1

                if record_action_tape:
                    pre_state_sha, pre_context_sha, pre_tick = tape_identity(state)
                    if pre_tick != tick:
                        raise ValueError("action tape tick differs from actual episode step")
                    observation = np.asarray(jax.device_get(state.obs['state'])).tolist()
                    before_explorer = _explorer_state_record(explorer_state) if explorer else None
                    if explorer:
                        action, explorer_state = _residual_action(explorer, observation, nominal_array,
                            goal, explorer_state, use_perturbation)
                        action = np.asarray(jax.device_get(action), dtype=np.float32)
                        requested_delta = np.asarray(jax.device_get(explorer_state.previous_delta))
                    else:
                        requested_delta = (np.asarray(direction['basis_vector'], dtype=np.float32)*np.float32(strength)
                                           if use_perturbation else np.zeros(4, dtype=np.float32))
                    tape_row = dict(tick=pre_tick, observation=observation,
                        state_sha256=pre_state_sha, context_sha256=pre_context_sha,
                        base_action=nominal_array.tolist(), applied_action=np.asarray(action).tolist(),
                        requested_delta=requested_delta.tolist(), effective_delta=(np.asarray(action)-nominal_array).tolist(),
                        previous_delta=previous_requested.tolist(),
                        controller_history=before_explorer['history'] if explorer else [])
                    if explorer:
                        tape_row.update(explorer_state_before=before_explorer,
                                        explorer_state_after=_explorer_state_record(explorer_state))
                    previous_requested = requested_delta.copy()
                state = step(state, action)
                jax.block_until_ready(state)
                interactions += 1
                peak_root_z_m = max(peak_root_z_m, _float(state.data.qpos[2]))
                nominal_actions.append(nominal_array.tolist())
                perturbed_actions.append(np.asarray(action, dtype=np.float32).tolist())
                effective_deltas.append((np.asarray(action) - nominal_array).tolist())

                if not _finite_state(state, action):
                    rejected = "nonfinite"
                    if dense: raise ValueError("nonfinite acquisition is an engineering error, not a boundary failure")
                    break
                if record_action_tape:
                    post_sha, post_context, post_tick = tape_identity(state)
                    if post_tick != tick+1:
                        raise ValueError("action tape post-action episode step mismatch")
                    tape_row.update(next_state_sha256=post_sha, next_context_sha256=post_context)
                    tape_records.append(tape_row)
                if _truth(state.info["expert_switching_used"]):
                    raise ValueError("causal Jump acquisition used expert switching")

                x_after = _float(state.data.qpos[0])
                if dense:
                    if _truth(state.info["down_events"].valid_contact_seen):
                        stop_reason = "first_valid_landing"
                        break
                    if _truth(state.done):
                        stop_reason = "task_terminated_before_landing"
                        break
                    if x_after > sample_x_max:
                        stop_reason = "sampling_x_guard"
                        break
                    capture_phase = next((p for p in ("upstream", "downstream") if _semantic_candidate(state, p)), None)
                    from .trajectory_sampling import observed_slice
                    selected = observed_slice(x_after, capture_phase, captured_bins,
                        spacing=slice_spacing_m, x_min=float(centerline["x_min_m"]),
                        x_max=sample_x_max)
                    if perturbation_started and selected is not None:
                        captured_bins.add((capture_phase, selected[0]))
                        saved_this_attempt += int(store_candidate(state, capture_phase, selected[1]))
                    if saved_this_attempt >= max_candidates_per_attempt:
                        stop_reason = "candidate_cap"
                        break
                    continue
                inside = abs(x_after - target_x) <= TARGET_HALF_WIDTH_M
                if inside and _semantic_candidate(state, phase):
                    candidate_state = state
                    break
                if x_after > target_x + TARGET_HALF_WIDTH_M:
                    rejected = "semantic_mismatch_or_slice_crossed"
                    break

            if dense:
                trajectory_receipts.append({"trajectory_id":trajectory_id,"proposer":str(policy_record["name"]),
                    "anchor_x_m":float(anchor["x_target_m"]),"strength":strength,"direction":direction,
                    "environment_interactions":interactions-attempt_start_interactions,
                    "candidate_count":saved_this_attempt,"stop_reason":stop_reason,
                    "perturbation_started":perturbation_started,
                    "final_x_m":_float(state.data.qpos[0]),
                    "peak_root_z_m":peak_root_z_m,
                    "peak_sampling":"control_step_states_including_reset",
                    "physical_failure":_truth(state.info.get("physical_failure",False)),
                    "timeout":_truth(state.info.get("timeout",False)),
                    "valid_landing":stop_reason=="first_valid_landing",
                    "truncated":stop_reason in {"sampling_x_guard","candidate_cap","forward_horizon_exhausted"}})
                if record_action_tape:
                    from ..action_tape import save_action_tape
                    final_identity = tape_identity(state)
                    tape_payload = dict(schema='jit_causal_action_tape_v1',protocol_sha256=protocol_sha,
                        trajectory_id=trajectory_id,policy_actor_sha256=str(policy_record['actor_sha256']),
                        policy_payload_sha256=str(policy_record['payload_sha256']),goal=goal,
                        initial_state_sha256=initial_identity[0],initial_context_sha256=initial_identity[1],
                        final_state_sha256=final_identity[0],final_context_sha256=final_identity[1],
                        record_count=len(tape_records),environment_interactions=interactions-attempt_start_interactions,
                        records=tape_records)
                    if explorer:
                        tape_payload.update(explorer_sha256=explorer['explorer_sha256'],
                            delta_limit=explorer['contract']['delta_limit'],slew_limit=explorer['contract']['slew_limit'])
                    relative_tape = Path('action_tapes') / f'trajectory_{attempt_index:06d}.json'
                    tape_sha = save_action_tape(output / relative_tape, tape_payload)
                    trajectory_receipts[-1]['lookback_m'] = lookback
                    trajectory_receipts[-1]['action_tape'] = {'path':str(relative_tape),'sha256':tape_sha}
                print(f"[causal] trajectory={trajectory_id} saved={saved_this_attempt} total_candidates={len(entries)} interactions={interactions}", flush=True)
                continue
            if candidate_state is None:
                exclusions[rejected or "forward_horizon_exhausted"] += 1
                continue
            if not perturbation_started or not perturbation_start_sha:
                exclusions["target_reached_before_perturbation_window"] += 1
                continue

            if not dense:
                store_candidate(candidate_state, phase, target_x)

    if interactions > maximum_interactions:
        raise ValueError("causal Jump acquisition exceeded predeclared interaction ceiling")
    report = {
        "schema": CATALOG_SCHEMA,
        "status": "completed",
        "artifact_role": "unlabeled_policy_conditioned_frontier_candidates",
        "split": "train",
        "iteration": int(policy_record["iteration"]),
        "policy_name": str(policy_record["name"]),
        "policy_actor_sha256": str(policy_record["actor_sha256"]),
        "policy_payload_sha256": str(policy_record["payload_sha256"]),
        "frozen_unified_manifest_sha256": str(frozen_manifest_sha256),
        "source_tube_manifest_sha256": str(artifact.manifest["manifest_sha256"]),
        "protocol_sha256": protocol_sha,
        "acquisition_mode": ACQUISITION_MODE,
        "jump_start_reachability_proven": True,
        "natural_start_connected": False,
        "rsi_used_for_reachability": False,
        "jump_start_state_sha256": jump_start_expected,
        "attempted_candidate_count": int(sum(phase_attempted.values())),
        "candidate_count": len(entries),
        "phase_attempted_candidate_counts": {
            phase: int(phase_attempted[phase])
            for phase in ("upstream", "downstream")
        },
        "phase_candidate_counts": {
            phase: int(phase_accepted[phase])
            for phase in ("upstream", "downstream")
        },
        "environment_interactions": int(interactions),
        "maximum_environment_interactions": int(maximum_interactions),
        "exclusion_counts": dict(sorted(exclusions.items())),
        "training_transitions": 0,
        "expert_switching_used": False,
        "test_data_used": False,
        "validation_data_used": False,
        "final_evaluation_data_used": False,
        "claim_boundary": {
            "unlabeled_acquisition_only": True,
            "tube_expansion_claim": False,
            "jce_jel_claim": False,
            "certified_safe_set_claim": False,
        },
        "entries": entries,
    }
    if record_action_tape:
        report.update(record_action_tape=True, action_tape_schema=protocol['action_tape_schema'],
                      controller_mode=protocol['controller_mode'])
    if explorer:
        report['residual_explorer'] = protocol['residual_explorer']
    if dense:
        if sum(r["environment_interactions"] for r in trajectory_receipts) != interactions:
            raise ValueError("trajectory interaction ledger mismatch")
        report["trajectory_receipts"] = trajectory_receipts
        report["trajectory_stop_counts"] = dict(Counter(r["stop_reason"] for r in trajectory_receipts))
    (output / "catalog.json").write_text(
        json.dumps(report, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    summary = {key: value for key, value in report.items() if key != "entries"}
    (output / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return report
