"""Role orchestration for ground-connected causal JIT frontier acquisition.

This module intentionally leaves the historical RSI-anchor frontier runner
untouched for reproducibility. Prospective causal plans are executed here:
proposal anchors identify locked centerline x slices only, while every physical
candidate starts at the authoritative natural ground reset and is generated by
real env.step dynamics before continuation RSI labeling.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import jax

from .acquisition.causal_jump import (
    ACQUISITION_MODE,
    collect_ground_connected_jump_candidates,
)
from .checkpoint import load_checkpoint
from .config import file_sha256
from .iterative_frontier_protocol import (
    ROLE_SCHEMA,
    ROLES,
    _acquisition_phase_support,
    _completed_acquisition,
    _completed_labeling,
    _load_plan,
    _logical_rows,
    _phase_counts,
    _read,
    _selected_policy,
    _source_tube,
    _verify_self_hash,
    _write,
    canonical_sha256,
)
from .ppo import make_checkpoint_policy
from .unified_continuation_labels import label_unified_continuations
from .unified_formal import build_unified_formal_environment
from .unified_training import checkpoint_identity


def _declared_role_anchors(plan: dict[str, Any], role: str) -> tuple[dict[str, Any], ...]:
    anchors = tuple(dict(row) for row in plan.get("anchors", ()) if row.get("role") == role)
    if not anchors:
        raise ValueError(f"causal frontier plan has no {role} proposal anchors")
    for row in anchors:
        if int(row.get("entry_index", 0)) != -1 or int(row.get("global_index", 0)) != -1:
            raise ValueError("causal proposal anchor unexpectedly references a Tube reset index")
        if row.get("proposal_anchor_is_physical_reset") is not False:
            raise ValueError("causal proposal anchor may not be a physical reset")
        if int(row.get("proposal_family_index", -1)) < 0:
            raise ValueError("causal proposal family index missing")
        if "x_target_m" not in row:
            raise ValueError("causal proposal target x missing")
    return anchors


def run_causal_frontier_role(
    *,
    plan_path: Path,
    role: str,
    output_dir: Path,
) -> dict[str, Any]:
    """Run/resume one causal TRAIN/CALIBRATION/ACCEPTANCE role."""
    role = str(role)
    if role not in ROLES:
        raise ValueError(f"role must be one of {ROLES}")
    output_dir = Path(output_dir)
    manifest_path = output_dir / "role_manifest.json"
    if manifest_path.is_file():
        existing = _read(manifest_path)
        _verify_self_hash(existing, "role_manifest_sha256")
        if existing.get("acquisition_mode") != ACQUISITION_MODE:
            raise ValueError("existing role manifest is not causal acquisition")
        return existing
    output_dir.mkdir(parents=True, exist_ok=True)

    plan = _load_plan(Path(plan_path))
    contract = plan.get("jump_tube_contract", {})
    panel = plan.get("fixed_probe_panel", {})
    if contract.get("acquisition_mode") != ACQUISITION_MODE:
        raise ValueError("causal role runner requires causal trajectory-centered plan")
    if contract.get("reachability_requirement") != "natural_start_connected_forward_env_step_only":
        raise ValueError("causal reachability contract drift")
    if contract.get("rsi_may_establish_forward_reachability") is not False:
        raise ValueError("RSI cannot establish causal forward reachability")
    if panel.get("acquisition_mode") != ACQUISITION_MODE:
        raise ValueError("causal probe panel mode drift")

    selected, record, frozen_path = _selected_policy(Path(str(plan["selected_policy"])))
    artifact = _source_tube(selected, record, Path(str(plan["source_tube"])))
    if artifact.manifest["manifest_sha256"] != plan["source_tube_manifest_sha256"]:
        raise ValueError("causal frontier source Tube drift")
    declared_anchors = _declared_role_anchors(plan, role)

    acquisition_dir = output_dir / "acquisition"
    labels_dir = output_dir / "labels"
    seeds = plan["seeds"][role]
    frozen_sha = file_sha256(frozen_path)

    acquisition = _completed_acquisition(
        acquisition_dir=acquisition_dir,
        policy_record=record,
        frozen_manifest_sha256=frozen_sha,
    )
    labeling = _completed_labeling(labels_dir)

    runtime_config = None
    runtime_artifact = None
    env = None
    policy = None

    def ensure_runtime() -> tuple[Any, Any]:
        nonlocal runtime_config, runtime_artifact, env, policy
        if env is None or policy is None:
            runtime_config, runtime_artifact, env = build_unified_formal_environment(
                Path(str(record["formal_config"]))
            )
            if runtime_artifact.manifest["manifest_sha256"] != artifact.manifest["manifest_sha256"]:
                raise ValueError("causal frontier runtime Tube drift")
            if env._bundle.xml_sha256 != record["xml_sha256"]:
                raise ValueError("causal frontier runtime XML drift")
            payload = load_checkpoint(
                Path(str(record["checkpoint"])),
                expected=checkpoint_identity(runtime_config, env),
            )
            policy = jax.jit(make_checkpoint_policy(env, payload, deterministic=True))
        return env, policy

    if acquisition is None:
        runtime_env, runtime_policy = ensure_runtime()
        acquisition = collect_ground_connected_jump_candidates(
            declared_anchors,
            acquisition_dir,
            env=runtime_env,
            policy=runtime_policy,
            policy_record=record,
            frozen_manifest_sha256=frozen_sha,
            nominal_centerline=Path(str(contract["nominal_centerline"])),
            protocol_seed=int(seeds["acquisition"]),
            strengths=tuple(float(x) for x in panel["strengths"]),
            action_names=tuple(str(x) for x in panel["action_names"]),
            signs=tuple(int(x) for x in panel["signs"]),
            lookbacks_m=tuple(float(x) for x in panel["causal_lookbacks_m"]),
            max_forward_ticks=int(panel["causal_forward_max_ticks"]),
        )
        if int(acquisition.get("candidate_count", 0)) <= 0:
            raise ValueError(f"causal frontier {role} acquisition produced no candidates")

    if acquisition.get("acquisition_mode") != ACQUISITION_MODE:
        raise ValueError("completed acquisition is not ground-connected causal mode")
    if acquisition.get("ground_reachability_proven") is not True:
        raise ValueError("completed acquisition lacks ground reachability proof")
    if acquisition.get("rsi_used_for_reachability") is not False:
        raise ValueError("completed acquisition used RSI for reachability")

    acquisition_phase_support = _acquisition_phase_support(acquisition, role=role)

    if labeling is None:
        runtime_env, runtime_policy = ensure_runtime()
        labeling = label_unified_continuations(
            acquisition_dir / "catalog.json",
            labels_dir,
            env=runtime_env,
            policy=runtime_policy,
            policy_record=record,
            frozen_manifest_sha256=frozen_sha,
            max_ticks=int(panel["max_label_ticks"]),
            protocol_seed=int(seeds["labeling"]),
        )

    logical_rows = _logical_rows(
        labels_dir=labels_dir,
        output_dir=output_dir,
        role=role,
        labeling=labeling,
    )
    phase_counts = _phase_counts(logical_rows, role=role)

    manifest = {
        "schema": ROLE_SCHEMA,
        "status": "completed",
        "iteration": int(plan["iteration"]),
        "role": role,
        "logical_split": role,
        "legacy_low_level_split_marker": "train",
        "legacy_marker_is_not_logical_data_role": True,
        "plan": str(plan_path),
        "plan_sha256": str(plan["plan_sha256"]),
        "selected_policy_sha256": str(plan["selected_policy_sha256"]),
        "policy_actor_sha256": str(record["actor_sha256"]),
        "policy_payload_sha256": str(record["payload_sha256"]),
        "source_tube_manifest_sha256": str(artifact.manifest["manifest_sha256"]),
        "acquisition_mode": ACQUISITION_MODE,
        "ground_reachability_proven": True,
        "rsi_used_for_reachability": False,
        "nominal_centerline": str(contract["nominal_centerline"]),
        "nominal_centerline_sha256": str(contract["nominal_centerline_sha256"]),
        "acquisition_phase_support": acquisition_phase_support,
        "logical_labels": str(output_dir / "logical_labels.json"),
        "logical_labels_file_sha256": file_sha256(output_dir / "logical_labels.json"),
        "source_acquisition_catalog": str(acquisition_dir / "catalog.json"),
        "source_acquisition_catalog_sha256": file_sha256(acquisition_dir / "catalog.json"),
        "source_label_summary": str(labels_dir / "summary.json"),
        "source_label_summary_sha256": file_sha256(labels_dir / "summary.json"),
        "phase_counts": phase_counts,
        "environment_interactions": int(acquisition["environment_interactions"])
        + int(labeling["environment_interactions"]),
        "training_transitions": 0,
        "expert_switching_used": False,
        "test_data_used": False,
        "final_evaluation_data_used": False,
        "claim_boundary": {
            "role_locked_before_next_policy_training": True,
            "forward_reachability_established_before_rsi_labeling": True,
            "rsi_establishes_reachability": False,
            "train_rows_may_fit_fields": role == "train",
            "rows_may_calibrate_thresholds": role == "calibration",
            "rows_may_gate_next_policy": role == "acceptance",
            "rows_may_enter_tube": role == "train",
            "certified_safe_set_claim": False,
            "jce_jel_claim": False,
        },
    }
    manifest["role_manifest_sha256"] = canonical_sha256(manifest)
    _write(manifest_path, manifest)
    return manifest
